=== limpkin/mooltipass/scripts/unicode_layout_parser/cldr-keyboards-32/keyboards/dtd/ldmlKeyboard.dtd
<!--
Copyright Â© 2003-2017 Unicode, Inc. and others. All rights reserved. Distributed under the Terms of Use in http://www.unicode.org/copyright.html.

Permission is hereby granted, free of charge, to any person obtaining a copy of the Unicode data files and any associated documentation (the "Data Files") or Unicode software and any associated documentation (the "Software") to deal in the Data Files or Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Data Files or Software, and to permit persons to whom the Data Files or Software are furnished to do so, provided that (a) the above copyright notice(s) and this permission notice appear with all copies of the Data Files or Software, (b) both the above copyright notice(s) and this permission notice appear in associated documentation, and (c) there is clear notice in each modified Data File or in the Software as well as in the documentation associated with the Data File(s) or Software that the data or software has been modified.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall not be used in advertising or otherwise to promote the sale, use or other dealings in these Data Files or Software without prior written authorization of the copyright holder.

    $Revision: 13338 $
-->

<!ELEMENT keyboard ( version, generation?, names, settings?, keyMap+, transforms? ) >
<!ATTLIST keyboard locale CDATA #REQUIRED >

<!ELEMENT version EMPTY >
<!ATTLIST version platform CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST version number CDATA #REQUIRED >
    <!--@METADATA-->
<!ATTLIST version cldrVersion CDATA #FIXED "32" >
    <!--@METADATA-->

<!ELEMENT generation EMPTY >
    <!--@DEPRECATED-->
<!ATTLIST generation date CDATA #REQUIRED >
    <!--@VALUE-->
    <!--@DEPRECATED-->

<!ELEMENT names ( name+ ) >

<!ELEMENT name EMPTY >
<!ATTLIST name value CDATA #REQUIRED >
    <!--@VALUE-->

<!ELEMENT settings EMPTY >
    <!--@ORDERED-->
<!ATTLIST settings fallback (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformFailure (omit) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST settings transformPartial (hide) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT keyMap ( map+ ) >
<!ATTLIST keyMap modifiers CDATA #IMPLIED >

<!ELEMENT map EMPTY >
<!ATTLIST map iso CDATA #REQUIRED >
<!ATTLIST map to CDATA #REQUIRED >
    <!--@VALUE-->
<!ATTLIST map longPress CDATA #IMPLIED >
    <!--@VALUE-->
<!ATTLIST map transform (no) #IMPLIED >
    <!--@VALUE-->

<!ELEMENT transforms ( transform+ ) >
<!ATTLIST transforms type CDATA #REQUIRED >

<!ELEMENT transform EMPTY >
<!ATTLIST transform from CDATA #REQUIRED >
<!ATTLIST transform to CDATA #REQUIRED >
    <!--@VALUE-->

=== limpkin/mooltipass/scripts/unicode_layout_parser/cldr-keyboards-32/keyboards/windows/got-t-k0-windows.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="got-t-k0-windows">
	<version platform="10" number="$Revision: 13680 $"/>
	<names>
		<name value="Gothic"/>
	</names>
	<settings fallback="omit"/>
	<keyMap>
		<map iso="E00" to="\u{331}\u{304}"/> <!-- `  to= ̱̄  -->
		<map iso="E01" to="1"/>
		<map iso="E02" to="2"/>
		<map iso="E03" to="3"/>
		<map iso="E04" to="4"/>
		<map iso="E05" to="5"/>
		<map iso="E06" to="6"/>
		<map iso="E07" to="7"/>
		<map iso="E08" to="8"/>
		<map iso="E09" to="9"/>
		<map iso="E10" to="0"/>
		<map iso="E11" to="-"/>
		<map iso="E12" to="="/>
		<map iso="D01" to="\u{335}"/> <!-- Q  to= ̵  -->
		<map iso="D02" to="\u{345}"/> <!-- W  to= ͅ  -->
		<map iso="D03" to="\u{334}"/> <!-- E  to= ̴  -->
		<map iso="D04" to="\u{342}"/> <!-- R  to= ͂  -->
		<map iso="D05" to="\u{344}"/> <!-- T  to= ̈́  -->
		<map iso="D06" to="𐌹\u{308}"/> <!-- Y  to= 𐌹̈  -->
		<map iso="D07" to="\u{33F}"/> <!-- U  to= ̿  -->
		<map iso="D08" to="\u{339}"/> <!-- I  to= ̹  -->
		<map iso="D09" to="\u{349}"/> <!-- O  to= ͉  -->
		<map iso="D10" to="\u{340}"/> <!-- P  to= ̀  -->
		<map iso="D11" to="\u{341}"/> <!-- [  to= ́  -->
		<map iso="D12" to="\u{34A}"/> <!-- ]  to= ͊  -->
		<map iso="C01" to="\u{330}"/> <!-- A  to= ̰  -->
		<map iso="C02" to="\u{343}"/> <!-- S  to= ̓  -->
		<map iso="C03" to="\u{333}"/> <!-- D  to= ̳  -->
		<map iso="C04" to="\u{346}"/> <!-- F  to= ͆  -->
		<map iso="C05" to="\u{332}"/> <!-- G  to= ̲  -->
		<map iso="C06" to="\u{337}"/> <!-- H  to= ̷  -->
		<map iso="C07" to="\u{33E}"/> <!-- J  to= ̾  -->
		<map iso="C08" to="\u{33A}"/> <!-- K  to= ̺  -->
		<map iso="C09" to="\u{33B}"/> <!-- L  to= ̻  -->
		<map iso="C10" to=":"/> <!-- ; -->
		<map iso="C11" to="&apos;"/>
		<map iso="C12" to="\u{305}"/> <!-- (key to right of ')  to= ̅  -->
		<map iso="B01" to="\u{336}"/> <!-- Z  to= ̶  -->
		<map iso="B02" to="\u{347}"/> <!-- X  to= ͇  -->
		<map iso="B03" to="\u{338}"/> <!-- C  to= ̸  -->
		<map iso="B04" to="\u{348}"/> <!-- V  to= ͈  -->
		<map iso="B05" to="\u{331}"/> <!-- B  to= ̱  -->
		<map iso="B06" to="\u{33D}"/> <!-- N  to= ̽  -->
		<map iso="B07" to="\u{33C}"/> <!-- M  to= ̼  -->
		<map iso="B08" to=","/>
		<map iso="B09" to="."/>
		<map iso="B10" to="·"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift+caps?">
		<map iso="E00" to="~"/> <!-- `  base=̱̄ -->
		<map iso="E01" to="!"/> <!-- 1 -->
		<map iso="E02" to="@"/> <!-- 2 -->
		<map iso="E03" to="#"/> <!-- 3 -->
		<map iso="E04" to="$"/> <!-- 4 -->
		<map iso="E05" to="%"/> <!-- 5 -->
		<map iso="E06" to="^"/> <!-- 6 -->
		<map iso="E07" to="&amp;"/> <!-- 7 -->
		<map iso="E08" to="*"/> <!-- 8 -->
		<map iso="E09" to="("/> <!-- 9 -->
		<map iso="E10" to=")"/> <!-- 0 -->
		<map iso="E11" to="_"/> <!-- - -->
		<map iso="E12" to="+"/> <!-- = -->
		<map iso="D11" to="["/> <!--   base=́ -->
		<map iso="D12" to="]"/> <!--   base=͊ -->
		<map iso="C10" to=";"/> <!--   base=: -->
		<map iso="C11" to="\u{22}"/> <!-- '  to= "  -->
		<map iso="C12" to="\"/> <!-- (key to right of ')  base=̅ -->
		<map iso="B08" to="&lt;"/> <!-- , -->
		<map iso="B09" to="&gt;"/> <!-- . -->
		<map iso="B10" to="/"/> <!--   base=· -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
</keyboard>

=== limpkin/mooltipass/scripts/unicode_layout_parser/cldr-keyboards-32/keyboards/android/lv-t-k0-android.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="lv-t-k0-android">
	<version platform="4.4" number="$Revision: 11914 $"/>
	<names>
		<name value="Latvian"/>
	</names>
	<keyMap>
		<map iso="D01" to="q"/>
		<map iso="D02" to="w"/>
		<map iso="D03" to="e" longPress="ē ė è é ê ë ę ě"/>
		<map iso="D04" to="r" longPress="ŗ ř ŕ"/>
		<map iso="D05" to="t" longPress="ţ ť"/>
		<map iso="D06" to="y" longPress="ý ÿ"/>
		<map iso="D07" to="u" longPress="ū ų ù ú û ü ů ű"/>
		<map iso="D08" to="i" longPress="ī į ì í î ï ı"/>
		<map iso="D09" to="o" longPress="ò ó ô õ ö œ ő ø"/>
		<map iso="D10" to="p"/>
		<map iso="C01" to="a" longPress="ā à á â ã ä å æ ą"/>
		<map iso="C02" to="s" longPress="š ß ś ş"/>
		<map iso="C03" to="d" longPress="ď"/>
		<map iso="C04" to="f"/>
		<map iso="C05" to="g" longPress="ģ ğ"/>
		<map iso="C06" to="h"/>
		<map iso="C07" to="j"/>
		<map iso="C08" to="k" longPress="ķ"/>
		<map iso="C09" to="l" longPress="ļ ł ĺ ľ"/>
		<map iso="B01" to="z" longPress="ž ż ź"/>
		<map iso="B02" to="x"/>
		<map iso="B03" to="c" longPress="č ç ć"/>
		<map iso="B04" to="v"/>
		<map iso="B05" to="b"/>
		<map iso="B06" to="n" longPress="ņ ñ ń ń"/>
		<map iso="B07" to="m"/>
		<map iso="A02" to=","/> <!-- (key to left of space) -->
		<map iso="A03" to=" "/> <!-- space -->
		<map iso="A04" to="." longPress="# ! , ? - : ' @"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="shift caps">
		<map iso="D01" to="Q"/>
		<map iso="D02" to="W"/>
		<map iso="D03" to="E" longPress="Ē Ė È É Ê Ë Ę Ě"/>
		<map iso="D04" to="R" longPress="Ŗ Ř Ŕ"/>
		<map iso="D05" to="T" longPress="Ţ Ť"/>
		<map iso="D06" to="Y" longPress="Ý Ÿ"/>
		<map iso="D07" to="U" longPress="Ū Ų Ù Ú Û Ü Ů Ű"/>
		<map iso="D08" to="I" longPress="Ī Į Ì Í Î Ï I"/>
		<map iso="D09" to="O" longPress="Ò Ó Ô Õ Ö Œ Ő Ø"/>
		<map iso="D10" to="P"/>
		<map iso="C01" to="A" longPress="Ā À Á Â Ã Ä Å Æ Ą"/>
		<map iso="C02" to="S" longPress="Š SS Ś Ş"/>
		<map iso="C03" to="D" longPress="Ď"/>
		<map iso="C04" to="F"/>
		<map iso="C05" to="G" longPress="Ģ Ğ"/>
		<map iso="C06" to="H"/>
		<map iso="C07" to="J"/>
		<map iso="C08" to="K" longPress="Ķ"/>
		<map iso="C09" to="L" longPress="Ļ Ł Ĺ Ľ"/>
		<map iso="B01" to="Z" longPress="Ž Ż Ź"/>
		<map iso="B02" to="X"/>
		<map iso="B03" to="C" longPress="Č Ç Ć"/>
		<map iso="B04" to="V"/>
		<map iso="B05" to="B"/>
		<map iso="B06" to="N" longPress="Ņ Ñ Ń Ń"/>
		<map iso="B07" to="M"/>
		<map iso="A02" to=","/> <!-- (key to left of space) -->
		<map iso="A03" to=" "/> <!-- space -->
		<map iso="A04" to="." longPress="# ! , ? - : ' @"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt">
		<map iso="D01" to="1" longPress="¹ ½ ⅓ ¼ ⅛"/> <!-- Q -->
		<map iso="D02" to="2" longPress="² ⅔"/> <!-- W -->
		<map iso="D03" to="3" longPress="³ ¾ ⅜"/> <!-- E -->
		<map iso="D04" to="4" longPress="⁴"/> <!-- R -->
		<map iso="D05" to="5" longPress="⅝"/> <!-- T -->
		<map iso="D06" to="6"/> <!-- Y -->
		<map iso="D07" to="7" longPress="⅞"/> <!-- U -->
		<map iso="D08" to="8"/> <!-- I -->
		<map iso="D09" to="9"/> <!-- O -->
		<map iso="D10" to="0" longPress="ⁿ ∅"/> <!-- P -->
		<map iso="C01" to="@"/> <!-- A -->
		<map iso="C02" to="#"/> <!-- S -->
		<map iso="C03" to="$" longPress="¢ £ € ¥ ₱"/> <!-- D -->
		<map iso="C04" to="%" longPress="‰"/> <!-- F -->
		<map iso="C05" to="&amp;"/> <!-- G -->
		<map iso="C06" to="-" longPress="_ – — ·"/> <!-- H -->
		<map iso="C07" to="+" longPress="±"/> <!-- J -->
		<map iso="C08" to="(" longPress="&lt; { ["/> <!-- K -->
		<map iso="C09" to=")" longPress="&gt; } ]"/> <!-- L -->
		<map iso="B01" to="*" longPress="† ‡ ★"/> <!-- Z -->
		<map iso="B02" to="\u{22}" longPress="“ ” « »"/> <!-- X  to= "  -->
		<map iso="B03" to="&apos;" longPress="‘ ’ ‹ ›"/> <!-- C -->
		<map iso="B04" to=":"/> <!-- V -->
		<map iso="B05" to=";"/> <!-- B -->
		<map iso="B06" to="!" longPress="¡"/> <!-- N -->
		<map iso="B07" to="?" longPress="¿"/> <!-- M -->
		<map iso="A00" to="_"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="/"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space)  base=, -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="." longPress="…"/> <!-- (key to right of space) -->
	</keyMap>
	<keyMap modifiers="opt+shift">
		<map iso="D01" to="~"/> <!-- Q -->
		<map iso="D02" to="`"/> <!-- W -->
		<map iso="D03" to="|"/> <!-- E -->
		<map iso="D04" to="•" longPress="♪ ♥ ♠ ♦ ♣"/> <!-- R -->
		<map iso="D05" to="√"/> <!-- T -->
		<map iso="D06" to="Π" longPress="π"/> <!-- Y -->
		<map iso="D07" to="÷"/> <!-- U -->
		<map iso="D08" to="×"/> <!-- I -->
		<map iso="D09" to="¶" longPress="§"/> <!-- O -->
		<map iso="D10" to="∆"/> <!-- P -->
		<map iso="C01" to="£"/> <!-- A -->
		<map iso="C02" to="¢"/> <!-- S -->
		<map iso="C03" to="€"/> <!-- D -->
		<map iso="C04" to="¥"/> <!-- F -->
		<map iso="C05" to="^" longPress="↑ ↓ ← →"/> <!-- G -->
		<map iso="C06" to="°" longPress="′ ″"/> <!-- H -->
		<map iso="C07" to="=" longPress="≠ ≈ ∞"/> <!-- J -->
		<map iso="C08" to="{"/> <!-- K -->
		<map iso="C09" to="}"/> <!-- L -->
		<map iso="B01" to="\"/> <!-- Z -->
		<map iso="B02" to="©"/> <!-- X -->
		<map iso="B03" to="®"/> <!-- C -->
		<map iso="B04" to="™"/> <!-- V -->
		<map iso="B05" to="℅"/> <!-- B -->
		<map iso="B06" to="["/> <!-- N -->
		<map iso="B07" to="]"/> <!-- M -->
		<map iso="A00" to="&lt;" longPress="‹ ≤ «"/> <!-- (3 keys to left of space) -->
		<map iso="A01" to="&gt;" longPress="› ≥ »"/> <!-- (2 keys to left of space) -->
		<map iso="A02" to=" "/> <!-- (key to left of space)  base=, -->
		<map iso="A03" to=","/> <!-- space -->
		<map iso="A04" to="." longPress="…"/> <!-- (key to right of space) -->
	</keyMap>
</keyboard>

=== limpkin/mooltipass/scripts/unicode_layout_parser/cldr-keyboards-32/keyboards/windows/ckb-t-k0-windows.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="ckb-t-k0-windows">
	<version platform="10" number="$Revision: 13265 $"/>
	<names>
		<name value="Central Kurdish"/>
	</names>
	<settings fallback="omit"/>
	<keyMap>
		<map iso="E00" to="`"/>
		<map iso="E01" to="١"/> <!-- 1 -->
		<map iso="E02" to="٢"/> <!-- 2 -->
		<map iso="E03" to="٣"/> <!-- 3 -->
		<map iso="E04" to="٤"/> <!-- 4 -->
		<map iso="E05" to="٥"/> <!-- 5 -->
		<map iso="E06" to="٦"/> <!-- 6 -->
		<map iso="E07" to="٧"/> <!-- 7 -->
		<map iso="E08" to="٨"/> <!-- 8 -->
		<map iso="E09" to="٩"/> <!-- 9 -->
		<map iso="E10" to="٠"/> <!-- 0 -->
		<map iso="E11" to="-"/>
		<map iso="E12" to="="/>
		<map iso="D01" to="ق"/> <!-- Q -->
		<map iso="D02" to="و"/> <!-- W -->
		<map iso="D03" to="ە"/> <!-- E -->
		<map iso="D04" to="ر"/> <!-- R -->
		<map iso="D05" to="ت"/> <!-- T -->
		<map iso="D06" to="ی"/> <!-- Y -->
		<map iso="D07" to="ئ"/> <!-- U -->
		<map iso="D08" to="ح"/> <!-- I -->
		<map iso="D09" to="ۆ"/> <!-- O -->
		<map iso="D10" to="پ"/> <!-- P -->
		<map iso="D11" to="]"/> <!-- [ -->
		<map iso="D12" to="["/> <!-- ] -->
		<map iso="C01" to="ا"/> <!-- A -->
		<map iso="C02" to="س"/> <!-- S -->
		<map iso="C03" to="د"/> <!-- D -->
		<map iso="C04" to="ف"/> <!-- F -->
		<map iso="C05" to="گ"/> <!-- G -->
		<map iso="C06" to="ه"/> <!-- H -->
		<map iso="C07" to="ژ"/> <!-- J -->
		<map iso="C08" to="ک"/> <!-- K -->
		<map iso="C09" to="ل"/> <!-- L -->
		<map iso="C10" to="؛"/> <!-- ; -->
		<map iso="C11" to="&apos;"/>
		<map iso="C12" to="\"/> <!-- (key to right of ') -->
		<map iso="B00" to="\"/> <!-- (key to left of Z) -->
		<map iso="B01" to="ز"/> <!-- Z -->
		<map iso="B02" to="خ"/> <!-- X -->
		<map iso="B03" to="ج"/> <!-- C -->
		<map iso="B04" to="ڤ"/> <!-- V -->
		<map iso="B05" to="ب"/> <!-- B -->
		<map iso="B06" to="ن"/> <!-- N -->
		<map iso="B07" to="م"/> <!-- M -->
		<map iso="B08" to="،"/> <!-- , -->
		<map iso="B09" to="."/>
		<map iso="B10" to="/"/>
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift+caps?">
		<map iso="E00" to="~"/> <!-- ` -->
		<map iso="E01" to="!"/> <!-- 1  base=١ -->
		<map iso="E02" to="@"/> <!-- 2  base=٢ -->
		<map iso="E03" to="#"/> <!-- 3  base=٣ -->
		<map iso="E04" to="$"/> <!-- 4  base=٤ -->
		<map iso="E05" to="٪"/> <!-- 5  base=٥ -->
		<map iso="E06" to="^"/> <!-- 6  base=٦ -->
		<map iso="E07" to="&amp;"/> <!-- 7  base=٧ -->
		<map iso="E08" to="*"/> <!-- 8  base=٨ -->
		<map iso="E09" to=")"/> <!-- 9  base=٩ -->
		<map iso="E10" to="("/> <!-- 0  base=٠ -->
		<map iso="E11" to="_"/> <!-- - -->
		<map iso="E12" to="+"/> <!-- = -->
		<map iso="D01" to="`"/> <!-- Q  base=ق -->
		<map iso="D02" to="وو"/> <!-- W  base=و -->
		<map iso="D03" to="ي"/> <!-- E  base=ە -->
		<map iso="D04" to="ڕ"/> <!-- R  base=ر -->
		<map iso="D05" to="ط"/> <!-- T  base=ت -->
		<map iso="D06" to="ێ"/> <!-- Y  base=ی -->
		<map iso="D07" to="ء"/> <!-- U  base=ئ -->
		<map iso="D08" to="ع"/> <!-- I  base=ح -->
		<map iso="D09" to="ؤ"/> <!-- O  base=ۆ -->
		<map iso="D10" to="ث"/> <!-- P  base=پ -->
		<map iso="D11" to="}"/> <!-- [  base=] -->
		<map iso="D12" to="{"/> <!-- ]  base=[ -->
		<map iso="C01" to="آ"/> <!-- A  base=ا -->
		<map iso="C02" to="ش"/> <!-- S  base=س -->
		<map iso="C03" to="ذ"/> <!-- D  base=د -->
		<map iso="C04" to="إ"/> <!-- F  base=ف -->
		<map iso="C05" to="غ"/> <!-- G  base=گ -->
		<map iso="C06" to="\u{200C}"/> <!-- H  base=ه -->
		<map iso="C07" to="أ"/> <!-- J  base=ژ -->
		<map iso="C08" to="ك"/> <!-- K  base=ک -->
		<map iso="C09" to="ڵ"/> <!-- L  base=ل -->
		<map iso="C10" to=":"/> <!-- ;  base=؛ -->
		<map iso="C11" to="\u{22}"/> <!-- '  to= "  -->
		<map iso="C12" to="|"/> <!-- (key to right of ')  base=\ -->
		<map iso="B00" to="/"/> <!-- (key to left of Z)  base=\ -->
		<map iso="B01" to="ض"/> <!-- Z  base=ز -->
		<map iso="B02" to="ص"/> <!-- X  base=خ -->
		<map iso="B03" to="چ"/> <!-- C  base=ج -->
		<map iso="B04" to="ظ"/> <!-- V  base=ڤ -->
		<map iso="B05" to="ى"/> <!-- B  base=ب -->
		<map iso="B06" to="ة"/> <!-- N  base=ن -->
		<map iso="B07" to="ـ"/> <!-- M  base=م -->
		<map iso="B08" to="&gt;"/> <!-- ,  base=، -->
		<map iso="B09" to="&lt;"/> <!-- . -->
		<map iso="B10" to="؟"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="ctrl+caps?">
		<map iso="D11" to="\u{1B}"/> <!-- [  base=] -->
		<map iso="D12" to="\u{1D}"/> <!-- ]  base=[ -->
		<map iso="C11" to="\u{1C}"/> <!-- ' -->
		<map iso="C12" to="\u{1C}"/> <!-- (key to right of ')  base=\ -->
	</keyMap>
	<keyMap modifiers="ctrl+shift+caps?">
		<map iso="E01" to="\u{200D}"/> <!-- 1  base=١ -->
		<map iso="E02" to="\u{200C}"/> <!-- 2  base=٢ -->
		<map iso="E03" to="\u{200E}"/> <!-- 3  base=٣ -->
		<map iso="E04" to="\u{200F}"/> <!-- 4  base=٤ -->
	</keyMap>
</keyboard>

=== limpkin/mooltipass/scripts/unicode_layout_parser/cldr-keyboards-32/keyboards/windows/syr-t-k0-windows-qwerty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "../dtd/ldmlKeyboard.dtd">
<keyboard locale="syr-t-k0-windows-qwerty">
	<version platform="10" number="$Revision: 13265 $"/>
	<names>
		<name value="Syriac Phonetic"/>
	</names>
	<settings fallback="omit"/>
	<keyMap>
		<map iso="E00" to="\u{70F}"/> <!-- ` -->
		<map iso="E01" to="1"/>
		<map iso="E02" to="2"/>
		<map iso="E03" to="3"/>
		<map iso="E04" to="4"/>
		<map iso="E05" to="5"/>
		<map iso="E06" to="6"/>
		<map iso="E07" to="7"/>
		<map iso="E08" to="8"/>
		<map iso="E09" to="9"/>
		<map iso="E10" to="0"/>
		<map iso="E11" to="-"/>
		<map iso="E12" to="="/>
		<map iso="D01" to="ܩ"/> <!-- Q -->
		<map iso="D02" to="ܘ"/> <!-- W -->
		<map iso="D03" to="ܖ"/> <!-- E -->
		<map iso="D04" to="ܪ"/> <!-- R -->
		<map iso="D05" to="ܬ"/> <!-- T -->
		<map iso="D06" to="ܝ"/> <!-- Y -->
		<map iso="D07" to="ܜ"/> <!-- U -->
		<map iso="D08" to="ܥ"/> <!-- I -->
		<map iso="D09" to="ܧ"/> <!-- O -->
		<map iso="D10" to="ܦ"/> <!-- P -->
		<map iso="D11" to="]"/> <!-- [ -->
		<map iso="D12" to="["/> <!-- ] -->
		<map iso="C01" to="ܐ"/> <!-- A -->
		<map iso="C02" to="ܣ"/> <!-- S -->
		<map iso="C03" to="ܕ"/> <!-- D -->
		<map iso="C04" to="ܔ"/> <!-- F -->
		<map iso="C05" to="ܓ"/> <!-- G -->
		<map iso="C06" to="ܗ"/> <!-- H -->
		<map iso="C07" to="ܛ"/> <!-- J -->
		<map iso="C08" to="ܟ"/> <!-- K -->
		<map iso="C09" to="ܠ"/> <!-- L -->
		<map iso="C10" to="ܚ"/> <!-- ; -->
		<map iso="C11" to="ܞ"/> <!-- ' -->
		<map iso="C12" to="܆"/> <!-- (key to right of ') -->
		<map iso="B00" to="܆"/> <!-- (key to left of Z) -->
		<map iso="B01" to="ܙ"/> <!-- Z -->
		<map iso="B02" to="ܨ"/> <!-- X -->
		<map iso="B03" to="ܤ"/> <!-- C -->
		<map iso="B04" to="ܫ"/> <!-- V -->
		<map iso="B05" to="ܒ"/> <!-- B -->
		<map iso="B06" to="ܢ"/> <!-- N -->
		<map iso="B07" to="ܡ"/> <!-- M -->
		<map iso="B08" to="܀"/> <!-- , -->
		<map iso="B09" to="."/>
		<map iso="B10" to="܇"/> <!-- / -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="shift+caps?">
		<map iso="E00" to="\u{32E}"/> <!-- `  base=܏  to= ̮  -->
		<map iso="E01" to="!"/> <!-- 1 -->
		<map iso="E02" to="\u{30A}"/> <!-- 2  to= ̊  -->
		<map iso="E03" to="\u{325}"/> <!-- 3  to= ̥  -->
		<map iso="E04" to="\u{749}"/> <!-- 4  to= ݉  -->
		<map iso="E05" to="♰"/> <!-- 5 -->
		<map iso="E06" to="♱"/> <!-- 6 -->
		<map iso="E07" to="܊"/> <!-- 7 -->
		<map iso="E08" to="»"/> <!-- 8 -->
		<map iso="E09" to=")"/> <!-- 9 -->
		<map iso="E10" to="("/> <!-- 0 -->
		<map iso="E11" to="«"/> <!-- - -->
		<map iso="E12" to="+"/> <!-- = -->
		<map iso="D01" to="\u{730}"/> <!-- Q  base=ܩ  to= ܰ  -->
		<map iso="D02" to="\u{733}"/> <!-- W  base=ܘ  to= ܳ  -->
		<map iso="D03" to="\u{736}"/> <!-- E  base=ܖ  to= ܶ  -->
		<map iso="D04" to="\u{73A}"/> <!-- R  base=ܪ  to= ܺ  -->
		<map iso="D05" to="\u{73D}"/> <!-- T  base=ܬ  to= ܽ  -->
		<map iso="D06" to="\u{740}"/> <!-- Y  base=ܝ  to= ݀  -->
		<map iso="D07" to="\u{741}"/> <!-- U  base=ܜ  to= ݁  -->
		<map iso="D08" to="\u{308}"/> <!-- I  base=ܥ  to= ̈  -->
		<map iso="D09" to="\u{304}"/> <!-- O  base=ܧ  to= ̄  -->
		<map iso="D10" to="\u{307}"/> <!-- P  base=ܦ  to= ̇  -->
		<map iso="D11" to="\u{303}"/> <!-- [  base=]  to= ̃  -->
		<map iso="D12" to="\u{74A}"/> <!-- ]  base=[  to= ݊  -->
		<map iso="C01" to="\u{731}"/> <!-- A  base=ܐ  to= ܱ  -->
		<map iso="C02" to="\u{734}"/> <!-- S  base=ܣ  to= ܴ  -->
		<map iso="C03" to="\u{737}"/> <!-- D  base=ܕ  to= ܷ  -->
		<map iso="C04" to="\u{73B}"/> <!-- F  base=ܔ  to= ܻ  -->
		<map iso="C05" to="\u{73E}"/> <!-- G  base=ܓ  to= ܾ  -->
		<map iso="C06" to="\u{711}"/> <!-- H  base=ܗ  to= ܑ  -->
		<map iso="C07" to="ـ"/> <!-- J  base=ܛ -->
		<map iso="C08" to="\u{324}"/> <!-- K  base=ܟ  to= ̤  -->
		<map iso="C09" to="\u{331}"/> <!-- L  base=ܠ  to= ̱  -->
		<map iso="C10" to="\u{323}"/> <!-- ;  base=ܚ  to= ̣  -->
		<map iso="C11" to="\u{330}"/> <!-- '  base=ܞ  to= ̰  -->
		<map iso="C12" to=":"/> <!-- (key to right of ')  base=܆ -->
		<map iso="B00" to=":"/> <!-- (key to left of Z)  base=܆ -->
		<map iso="B01" to="\u{732}"/> <!-- Z  base=ܙ  to= ܲ  -->
		<map iso="B02" to="\u{735}"/> <!-- X  base=ܨ  to= ܵ  -->
		<map iso="B03" to="\u{738}"/> <!-- C  base=ܤ  to= ܸ  -->
		<map iso="B04" to="\u{73C}"/> <!-- V  base=ܫ  to= ܼ  -->
		<map iso="B05" to="\u{73F}"/> <!-- B  base=ܒ  to= ܿ  -->
		<map iso="B06" to="\u{739}"/> <!-- N  base=ܢ  to= ܹ  -->
		<map iso="B07" to="\u{742}"/> <!-- M  base=ܡ  to= ݂  -->
		<map iso="B08" to="،"/> <!-- ,  base=܀ -->
		<map iso="B09" to="؛"/> <!-- . -->
		<map iso="B10" to="؟"/> <!-- /  base=܇ -->
		<map iso="A03" to=" "/> <!-- space -->
	</keyMap>
	<keyMap modifiers="altR+caps? ctrl+alt+caps?">
		<map iso="E00" to="\u{651}"/> <!-- `  base=܏  to= ّ  -->
		<map iso="E01" to="܁"/> <!-- 1 -->
		<map iso="E02" to="܂"/> <!-- 2 -->
		<map iso="E03" to="܃"/> <!-- 3 -->
		<map iso="E04" to="܄"/> <!-- 4 -->
		<map iso="E05" to="܅"/> <!-- 5 -->
		<map iso="E06" to="܈"/> <!-- 6 -->
		<map iso="E07" to="܉"/> <!-- 7 -->
		<map iso="E08" to="܋"/> <!-- 8 -->
		<map iso="E09" to="܌"/> <!-- 9 -->
		<map iso="E10" to="܍"/> <!-- 0 -->
		<map iso="E11" to="┌"/> <!-- - -->
		<map iso="E12" to="┐"/> <!-- = -->
		<map iso="D01" to="\u{64E}"/> <!-- Q  base=ܩ  to= َ  -->
		<map iso="D02" to="\u{64B}"/> <!-- W  base=ܘ  to= ً  -->
		<map iso="D03" to="\u{64F}"/> <!-- E  base=ܖ  to= ُ  -->
		<map iso="D04" to="\u{64C}"/> <!-- R  base=ܪ  to= ٌ  -->
		<map iso="D05" to="\u{653}"/> <!-- T  base=ܬ  to= ٓ  -->
		<map iso="D06" to="\u{654}"/> <!-- Y  base=ܝ  to= ٔ  -->
		<map iso="D07" to="\u{747}"/> <!-- U  base=ܜ  to= ݇  -->
		<map iso="D08" to="\u{743}"/> <!-- I  base=ܥ  to= ݃  -->
		<map iso="D09" to="\u{745}"/> <!-- O  base=ܧ  to= ݅  -->
		<map iso="D10" to="\u{32D}"/> <!-- P  base=ܦ  to= ̭  -->
		<map iso="C01" to="\u{650}"/> <!-- A  base=ܐ  to= ِ  -->
		<map iso="C02" to="\u{64D}"/> <!-- S  base=ܣ  to= ٍ  -->
		<map iso="C04" to="ء"/> <!-- F  base=ܔ -->
		<map iso="C05" to="\u{655}"/> <!-- G  base=ܓ  to= ٕ  -->
		<map iso="C06" to="\u{670}"/> <!-- H  base=ܗ  to= ٰ  -->
		<map iso="C07" to="\u{748}"/> <!-- J  base=ܛ  to= ݈  -->
		<map iso="C08" to="\u{744}"/> <!-- K  base=ܟ  to= ݄  -->
		<map iso="C09" to="\u{746}"/> <!-- L  base=ܠ  to= ݆  -->
		<map iso="B02" to="\u{652}"/> <!-- X  base=ܨ  to= ْ  -->
		<map iso="B04" to="\u{200D}"/> <!-- V  base=ܫ -->
		<map iso="B05" to="\u{200C}"/> <!-- B  base=ܒ -->
		<map iso="B06" to="\u{200E}"/> <!-- N  base=ܢ -->
		<map iso="B07" to="\u{200F}"/> <!-- M  base=ܡ -->
	</keyMap>
	<keyMap modifiers="ctrl+caps?">
		<map iso="D11" to="\u{1B}"/> <!-- [  base=] -->
		<map iso="D12" to="\u{1D}"/> <!-- ]  base=[ -->
		<map iso="C12" to="\u{1C}"/> <!-- (key to right of ')  base=܆ -->
	</keyMap>
</keyboard>
